#include "update.h"
#include <winhttp.h>
#include <wincrypt.h>
#include <shellapi.h>
#include <sddl.h>
#include <algorithm>
#include <atomic>
#include <cctype>
#include <map>
#include <sstream>
#include <stdexcept>
#include <limits>

namespace fiUpdate {
namespace {
const size_t MaximumInstaller=128*1024*1024, MaximumJson=1024*1024;
const wchar_t* Latest=L"https://api.github.com/repos/Watertube-bilibili/free-island/releases/latest";
const wchar_t* DownloadPrefix=L"https://github.com/Watertube-bilibili/free-island/releases/download/";
struct Lock { CRITICAL_SECTION* p; explicit Lock(CRITICAL_SECTION& s):p(&s){EnterCriticalSection(p);} ~Lock(){LeaveCriticalSection(p);} };
void Require(bool condition,const char* message){if(!condition)throw std::runtime_error(message);}
std::wstring Wide(const std::string& s){if(s.empty())return L"";int n=MultiByteToWideChar(CP_UTF8,MB_ERR_INVALID_CHARS,s.data(),(int)s.size(),NULL,0);Require(n>0,"Invalid UTF-8");std::wstring out(n,L'\0');MultiByteToWideChar(CP_UTF8,MB_ERR_INVALID_CHARS,s.data(),(int)s.size(),&out[0],n);return out;}
std::string Utf8(const std::wstring& s){if(s.empty())return "";int n=WideCharToMultiByte(CP_UTF8,WC_ERR_INVALID_CHARS,s.data(),(int)s.size(),NULL,0,NULL,NULL);Require(n>0,"Invalid Unicode");std::string out(n,'\0');WideCharToMultiByte(CP_UTF8,WC_ERR_INVALID_CHARS,s.data(),(int)s.size(),&out[0],n,NULL,NULL);return out;}
bool Version(const std::wstring& text,std::vector<unsigned>& parts){parts.clear();if(text.empty()||text.size()>32)return false;size_t start=text[0]==L'v'?1:0;for(int i=0;i<3;i++){size_t end=text.find(L'.',start);if(i==2)end=text.size();if(end==std::wstring::npos||end==start||end-start>5||(end-start>1&&text[start]==L'0'))return false;unsigned value=0;for(size_t j=start;j<end;j++){if(text[j]<L'0'||text[j]>L'9')return false;value=value*10+text[j]-L'0';}if(value>65535)return false;parts.push_back(value);start=end+1;}return start==text.size()+1;}
bool HashText(std::wstring& text){if(text.size()!=64)return false;for(wchar_t& c:text){if(c>=L'A'&&c<=L'F')c+=32;if(!((c>=L'0'&&c<=L'9')||(c>=L'a'&&c<=L'f')))return false;}return true;}
struct Json { char kind='n'; std::string text; std::map<std::string,Json> object; std::vector<Json> array; const Json& At(const char* key)const{static Json none;auto it=object.find(key);return it==object.end()?none:it->second;} };
class Parser {
 const std::string& s;size_t at=0,nodes=0;
 void Space(){while(at<s.size()&&(s[at]==' '||s[at]=='\r'||s[at]=='\n'||s[at]=='\t'))++at;}
 char Take(){Require(at<s.size(),"Truncated JSON");return s[at++];}
 unsigned Hex(){unsigned v=0;for(int i=0;i<4;i++){char c=Take();Require(std::isxdigit((unsigned char)c)!=0,"Invalid JSON escape");v=v*16+(c>='0'&&c<='9'?c-'0':std::tolower((unsigned char)c)-'a'+10);}return v;}
 std::string String(){Require(Take()=='"',"JSON string expected");std::string out;for(;;){char c=Take();if(c=='"')break;Require((unsigned char)c>=32,"JSON control character");if(c!='\\')out+=c;else{c=Take();if(c=='"'||c=='\\'||c=='/')out+=c;else if(c=='n')out+='\n';else if(c=='r')out+='\r';else if(c=='t')out+='\t';else if(c=='b')out+='\b';else if(c=='f')out+='\f';else if(c=='u'){std::wstring chars(1,(wchar_t)Hex());if(chars[0]>=0xd800&&chars[0]<=0xdbff){Require(Take()=='\\'&&Take()=='u',"Invalid surrogate");wchar_t low=(wchar_t)Hex();Require(low>=0xdc00&&low<=0xdfff,"Invalid surrogate");chars+=low;}else Require(chars[0]<0xdc00||chars[0]>0xdfff,"Invalid surrogate");out+=Utf8(chars);}else throw std::runtime_error("Invalid escape");}Require(out.size()<=262144,"JSON string too large");}Wide(out);return out;}
 Json Read(unsigned depth){Require(depth<32&&++nodes<30000,"JSON nesting too deep");Space();Require(at<s.size(),"Empty JSON");Json v;char c=s[at];if(c=='"'){v.kind='s';v.text=String();}else if(c=='{'||c=='['){++at;v.kind=c;Space();char end=c=='{'?'}':']';if(at<s.size()&&s[at]==end){++at;return v;}for(;;){Space();if(c=='{'){std::string key=String();Space();Require(Take()==':',"JSON colon expected");Require(v.object.emplace(key,Read(depth+1)).second,"Duplicate JSON key");}else v.array.push_back(Read(depth+1));Space();char next=Take();if(next==end)break;Require(next==',',"JSON comma expected");}}else if(c=='t'||c=='f'||c=='n'){const char* literal=c=='t'?"true":c=='f'?"false":"null";size_t n=strlen(literal);Require(s.compare(at,n,literal)==0,"Invalid JSON literal");v.kind=c;at+=n;}else{size_t begin=at;while(at<s.size()&&std::string("-+0123456789.eE").find(s[at])!=std::string::npos)++at;Require(at>begin,"Invalid JSON value");v.kind='d';v.text=s.substr(begin,at-begin);}return v;}
public: explicit Parser(const std::string& text):s(text){} Json Parse(){Require(s.size()<=MaximumJson,"JSON limit exceeded");Json v=Read(0);Space();Require(at==s.size(),"Trailing JSON");return v;}
};
unsigned long long Size(const Json& value){Require(value.kind=='d'&&!value.text.empty()&&value.text.size()<=12,"Invalid asset size");unsigned long long n=0;for(char c:value.text){Require(c>='0'&&c<='9',"Invalid asset size");n=n*10+c-'0';}return n;}
std::wstring String(const Json& value){Require(value.kind=='s',"Release field missing");return Wide(value.text);}
struct Internet { HINTERNET h=NULL; explicit Internet(HINTERNET value):h(value){Require(h!=NULL,"无法建立安全连接");} ~Internet(){if(h)WinHttpCloseHandle(h);} Internet(const Internet&)=delete; };
struct File { HANDLE h=INVALID_HANDLE_VALUE;explicit File(HANDLE value):h(value){Require(h!=INVALID_HANDLE_VALUE,"无法写入更新缓存");} ~File(){if(h!=INVALID_HANDLE_VALUE)CloseHandle(h);}void Close(){if(h!=INVALID_HANDLE_VALUE){CloseHandle(h);h=INVALID_HANDLE_VALUE;}} };
struct Digest { HCRYPTPROV provider=0;HCRYPTHASH hash=0;Digest(){Require(CryptAcquireContextW(&provider,NULL,NULL,PROV_RSA_AES,CRYPT_VERIFYCONTEXT)!=FALSE,"SHA-256 unavailable");if(!CryptCreateHash(provider,CALG_SHA_256,0,0,&hash)){CryptReleaseContext(provider,0);provider=0;throw std::runtime_error("SHA-256 unavailable");}}~Digest(){if(hash)CryptDestroyHash(hash);if(provider)CryptReleaseContext(provider,0);}void Add(const BYTE* p,size_t n){Require(n<=MAXDWORD&&CryptHashData(hash,p,(DWORD)n,0),"Hash failed");}std::wstring Finish(){BYTE bytes[32];DWORD n=32;Require(CryptGetHashParam(hash,HP_HASHVAL,bytes,&n,0)&&n==32,"Hash failed");const wchar_t*digits=L"0123456789abcdef";std::wstring value;for(BYTE b:bytes){value+=digits[b>>4];value+=digits[b&15];}return value;} };
void SafeDirectory(const std::wstring& directory){Require(directory.size()>3&&directory.size()<220&&directory[1]==L':'&&directory[2]==L'\\',"Unsafe update directory");for(size_t i=3;i<=directory.size();i++){if(i!=directory.size()&&directory[i]!=L'\\')continue;std::wstring p=directory.substr(0,i);DWORD a=GetFileAttributesW(p.c_str());if(a==INVALID_FILE_ATTRIBUTES){Require(CreateDirectoryW(p.c_str(),NULL)||GetLastError()==ERROR_ALREADY_EXISTS,"Cannot create update directory");a=GetFileAttributesW(p.c_str());}Require(a!=INVALID_FILE_ATTRIBUTES&&(a&FILE_ATTRIBUTE_DIRECTORY)&&!(a&FILE_ATTRIBUTE_REPARSE_POINT),"Unsafe update directory");}}
std::wstring Reg(const wchar_t* name){HKEY key;const wchar_t* path=L"Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\FreeIslandWin7";if(RegOpenKeyExW(HKEY_CURRENT_USER,path,0,KEY_QUERY_VALUE,&key)!=ERROR_SUCCESS)return L"";wchar_t value[2048]={};DWORD bytes=sizeof(value)-sizeof(wchar_t),type=0;LONG r=RegQueryValueExW(key,name,NULL,&type,(BYTE*)value,&bytes);RegCloseKey(key);return r==ERROR_SUCCESS&&type==REG_SZ?std::wstring(value):L"";}
std::wstring OwnerSid(){HANDLE token=NULL;Require(OpenProcessToken(GetCurrentProcess(),TOKEN_QUERY,&token)!=FALSE,"Cannot identify update owner");DWORD size=0;GetTokenInformation(token,TokenUser,NULL,0,&size);std::vector<BYTE> info(size);BOOL ok=size&&GetTokenInformation(token,TokenUser,info.data(),size,&size);CloseHandle(token);Require(ok!=FALSE,"Cannot identify update owner");LPWSTR text=NULL;Require(ConvertSidToStringSidW(((TOKEN_USER*)info.data())->User.Sid,&text)!=FALSE,"Cannot identify update owner");std::wstring result(text);LocalFree(text);return result;}
void HttpGet(const std::wstring& start,size_t limit,const Sink& sink,const std::atomic<bool>& cancel){
#if defined(FI_CORE_TESTING) || defined(FI_UPDATE_TESTING)
 (void)start;(void)limit;(void)sink;(void)cancel;throw std::runtime_error("Network disabled in test build");
#else
 Internet session(WinHttpOpen(L"FreeIslandWin7/Update",WINHTTP_ACCESS_TYPE_DEFAULT_PROXY,WINHTTP_NO_PROXY_NAME,WINHTTP_NO_PROXY_BYPASS,0));DWORD tls=0x00000800;Require(WinHttpSetOption(session.h,WINHTTP_OPTION_SECURE_PROTOCOLS,&tls,sizeof(tls))!=FALSE,"系统不支持 TLS 1.2");Require(WinHttpSetTimeouts(session.h,5000,5000,10000,10000)!=FALSE,"网络超时配置失败");std::wstring url=start;bool api=start==Latest;ULONGLONG deadline=GetTickCount64()+(api?30000:300000);
 for(int redirects=0;redirects<=4;redirects++){Require(!cancel&&GetTickCount64()<deadline,"更新已取消或超时");Require(AllowedUrl(url,api),"不允许的更新地址");URL_COMPONENTS parts={};parts.dwStructSize=sizeof(parts);parts.dwHostNameLength=parts.dwUrlPathLength=parts.dwExtraInfoLength=(DWORD)-1;Require(WinHttpCrackUrl(url.c_str(),0,0,&parts)!=FALSE,"更新地址无效");std::wstring host(parts.lpszHostName,parts.dwHostNameLength),path(parts.lpszUrlPath,parts.dwUrlPathLength);if(parts.dwExtraInfoLength)path.append(parts.lpszExtraInfo,parts.dwExtraInfoLength);Internet connection(WinHttpConnect(session.h,host.c_str(),INTERNET_DEFAULT_HTTPS_PORT,0));Internet request(WinHttpOpenRequest(connection.h,L"GET",path.c_str(),NULL,WINHTTP_NO_REFERER,WINHTTP_DEFAULT_ACCEPT_TYPES,WINHTTP_FLAG_SECURE));DWORD disabled=WINHTTP_DISABLE_REDIRECTS|WINHTTP_DISABLE_COOKIES|WINHTTP_DISABLE_AUTHENTICATION;Require(WinHttpSetOption(request.h,WINHTTP_OPTION_DISABLE_FEATURE,&disabled,sizeof(disabled))!=FALSE,"网络安全选项失败");DWORD autologon=WINHTTP_AUTOLOGON_SECURITY_LEVEL_HIGH;Require(WinHttpSetOption(request.h,WINHTTP_OPTION_AUTOLOGON_POLICY,&autologon,sizeof(autologon))!=FALSE,"网络安全选项失败");Require(WinHttpSendRequest(request.h,L"Accept: application/vnd.github+json\r\n",-1,WINHTTP_NO_REQUEST_DATA,0,0,0)&&WinHttpReceiveResponse(request.h,NULL),"无法连接 GitHub；请检查网络或 TLS 1.2 支持");DWORD code=0,size=sizeof(code);Require(WinHttpQueryHeaders(request.h,WINHTTP_QUERY_STATUS_CODE|WINHTTP_QUERY_FLAG_NUMBER,NULL,&code,&size,NULL)!=FALSE,"无法读取服务器状态");if(code==301||code==302||code==303||code==307||code==308){wchar_t location[8192];DWORD bytes=sizeof(location);Require(redirects<4&&WinHttpQueryHeaders(request.h,WINHTTP_QUERY_LOCATION,NULL,location,&bytes,NULL)&&bytes<sizeof(location),"更新跳转无效");url=location;continue;}Require(code==200,"GitHub 暂时不可用，请稍后重试");unsigned long long total=0;BYTE buffer[65536];for(;;){Require(!cancel&&GetTickCount64()<deadline,"更新已取消或超时");DWORD received=0;Require(WinHttpReadData(request.h,buffer,sizeof(buffer),&received)!=FALSE,"更新下载中断");if(!received)return;total+=received;Require(total<=limit,"更新文件超出大小限制");sink(buffer,received);} }
 throw std::runtime_error("更新跳转过多");
#endif
}
}

bool Newer(const std::wstring& candidate,const std::wstring& current){std::vector<unsigned>a,b;return Version(candidate,a)&&Version(current,b)&&a>b;}
bool AllowedUrl(const std::wstring& url,bool apiOnly){if(url.size()>8192||url.compare(0,8,L"https://")!=0||url.find_first_of(L"\r\n\t #\\")!=std::wstring::npos)return false;size_t end=url.find(L'/',8);if(end==std::wstring::npos)return false;std::wstring host=url.substr(8,end-8);if(apiOnly)return host==L"api.github.com"&&url==Latest;return host==L"github.com"||host==L"release-assets.githubusercontent.com"||host==L"objects.githubusercontent.com";}
Release ParseRelease(const std::string& text,const std::wstring& current){Json root=Parser(text).Parse();Require(root.kind=='{'&&root.At("draft").kind=='f'&&root.At("prerelease").kind=='f',"Release is not stable");std::wstring tag=String(root.At("tag_name"));std::vector<unsigned>parts;Require(Version(tag,parts)&&tag[0]==L'v',"Invalid stable version");Release r;r.version=tag.substr(1);if(!Newer(r.version,current)){r.version.clear();return r;}Require(String(root.At("html_url"))==L"https://github.com/Watertube-bilibili/free-island/releases/tag/"+tag,"Wrong repository release");r.filename=L"FreeIsland-Win7-Setup-"+r.version+L".exe";std::wstring manifest=L"SHA256SUMS-"+r.version+L".txt";Require(root.At("assets").kind=='[',"No release assets");bool found=false;for(const Json& asset:root.At("assets").array){std::wstring name=String(asset.At("name"));if(name!=r.filename&&name!=manifest)continue;Require(asset.At("state").kind=='s'&&asset.At("state").text=="uploaded","Incomplete release asset");std::wstring url=String(asset.At("browser_download_url"));Require(url==std::wstring(DownloadPrefix)+tag+L"/"+name,"Wrong asset URL");if(name==manifest){Require(r.manifestUrl.empty()&&Size(asset.At("size"))<=65536,"Invalid checksum manifest");r.manifestUrl=url;continue;}Require(!found,"Duplicate installer asset");found=true;r.assetUrl=url;r.size=Size(asset.At("size"));Require(r.size>0&&r.size<=MaximumInstaller,"Invalid installer size");if(asset.At("digest").kind=='s'){r.digest=Wide(asset.At("digest").text);Require(r.digest.compare(0,7,L"sha256:")==0,"Unsupported digest");r.digest.erase(0,7);Require(HashText(r.digest),"Invalid asset digest");}}Require(found&&(!r.digest.empty()||!r.manifestUrl.empty()),"Release has no verified Win7 installer");return r;}
std::wstring ManifestHash(const std::string& text,const std::wstring& filename){Require(text.size()<=65536,"Manifest limit exceeded");std::istringstream input(text);std::string line;std::wstring found;while(std::getline(input,line)){if(!line.empty()&&line.back()=='\r')line.pop_back();if(line.size()<67)continue;std::string name=line.substr(66);if(Wide(name)!=filename)continue;Require(found.empty()&&line[64]==' '&&(line[65]==' '||line[65]=='*'),"Ambiguous manifest");found=Wide(line.substr(0,64));Require(HashText(found),"Invalid manifest digest");}Require(!found.empty(),"Installer hash missing");return found;}
bool CanApply(bool visible,bool timer,bool shutdown,bool installed){return !visible&&!timer&&!shutdown&&installed;}
bool ProcessElevated(){HANDLE token=NULL;TOKEN_ELEVATION elevation={};DWORD length=0;if(!OpenProcessToken(GetCurrentProcess(),TOKEN_QUERY,&token))return true;bool ok=GetTokenInformation(token,TokenElevation,&elevation,sizeof(elevation),&length)!=FALSE;CloseHandle(token);return !ok||elevation.TokenIsElevated!=0;}
static unsigned long long UnixSeconds(){FILETIME ft;GetSystemTimeAsFileTime(&ft);ULARGE_INTEGER n;n.LowPart=ft.dwLowDateTime;n.HighPart=ft.dwHighDateTime;return n.QuadPart/10000000ULL-11644473600ULL;}
static bool RecentAttempt(const std::wstring& directory,const std::wstring& version){std::wstring path=directory+L"\\attempt-"+version+L".txt";HANDLE file=CreateFileW(path.c_str(),GENERIC_READ,FILE_SHARE_READ,NULL,OPEN_EXISTING,FILE_FLAG_OPEN_REPARSE_POINT,NULL);if(file==INVALID_HANDLE_VALUE)return false;char bytes[32]={};DWORD count=0;bool ok=ReadFile(file,bytes,sizeof(bytes)-1,&count,NULL)!=FALSE;CloseHandle(file);if(!ok)return true;unsigned long long saved=0;for(DWORD i=0;i<count;i++){if(bytes[i]<'0'||bytes[i]>'9')return true;saved=saved*10+bytes[i]-'0';}unsigned long long now=UnixSeconds();return saved>now||now-saved<86400;}
static bool ReceiptNeedsElevation(const std::wstring& directory,const std::wstring& version){try{std::wstring root=directory.substr(0,directory.find_last_of(L'\\'));File file(CreateFileW((root+L"\\update-result.txt").c_str(),GENERIC_READ,FILE_SHARE_READ,NULL,OPEN_EXISTING,FILE_FLAG_OPEN_REPARSE_POINT,NULL));BY_HANDLE_FILE_INFORMATION info;Require(GetFileInformationByHandle(file.h,&info)&&!(info.dwFileAttributes&FILE_ATTRIBUTE_REPARSE_POINT),"Unsafe receipt");char bytes[32768];DWORD count=0;Require(ReadFile(file.h,bytes,sizeof(bytes),&count,NULL)&&count<sizeof(bytes),"Invalid receipt");std::wstring text=Wide(std::string(bytes,count));return text.compare(0,8+version.size(),L"failed\n"+version+L"\n")==0&&text.find(L"（5）")!=std::wstring::npos;}catch(...){return false;}}
static void RecordAttempt(const std::wstring& directory,const std::wstring& version){SafeDirectory(directory);std::wstring path=directory+L"\\attempt-"+version+L".txt";DWORD attributes=GetFileAttributesW(path.c_str());Require(attributes==INVALID_FILE_ATTRIBUTES||!(attributes&(FILE_ATTRIBUTE_REPARSE_POINT|FILE_ATTRIBUTE_DIRECTORY)),"Unsafe update history");File file(CreateFileW(path.c_str(),GENERIC_WRITE,0,NULL,OPEN_ALWAYS,FILE_FLAG_OPEN_REPARSE_POINT,NULL));BY_HANDLE_FILE_INFORMATION info;Require(GetFileInformationByHandle(file.h,&info)&&info.nNumberOfLinks==1,"Unsafe update history");std::string text=std::to_string(UnixSeconds());DWORD written=0;Require(SetEndOfFile(file.h)&&WriteFile(file.h,text.data(),(DWORD)text.size(),&written,NULL)&&written==text.size()&&FlushFileBuffers(file.h),"Cannot save update history");}
std::wstring FileVersion(const std::wstring& path){DWORD ignored=0,size=GetFileVersionInfoSizeW(path.c_str(),&ignored);if(!size||size>2*1024*1024)return L"";std::vector<BYTE> bytes(size);if(!GetFileVersionInfoW(path.c_str(),0,size,bytes.data()))return L"";VS_FIXEDFILEINFO*info=NULL;UINT length=0;if(!VerQueryValueW(bytes.data(),L"\\",(void**)&info,&length)||length<sizeof(*info)||info->dwSignature!=0xfeef04bd)return L"";return std::to_wstring(HIWORD(info->dwFileVersionMS))+L"."+std::to_wstring(LOWORD(info->dwFileVersionMS))+L"."+std::to_wstring(HIWORD(info->dwFileVersionLS));}
std::wstring RegisteredDirectory(const std::wstring& executable){std::wstring path=Reg(L"InstallLocation");if(path.empty()||path.size()>220||_wcsicmp((path+L"\\FreeIslandWin7.exe").c_str(),executable.c_str()))return L"";if(Reg(L"UninstallString")!=L"\""+path+L"\\FreeIslandWin7.Uninstall.exe\" --uninstall")return L"";try{SafeDirectory(path);File file(CreateFileW((path+L"\\freeisland-win7.install").c_str(),GENERIC_READ,FILE_SHARE_READ,NULL,OPEN_EXISTING,FILE_FLAG_OPEN_REPARSE_POINT,NULL));BY_HANDLE_FILE_INFORMATION info;Require(GetFileInformationByHandle(file.h,&info)&&!(info.dwFileAttributes&FILE_ATTRIBUTE_REPARSE_POINT)&&info.nNumberOfLinks==1,"Unsafe marker");char marker[64]={};DWORD read=0;Require(ReadFile(file.h,marker,sizeof(marker)-1,&read,NULL)&&std::string(marker,read)=="FreeIsland.Win7.Install.v1\r\n","Unknown installation");return path;}catch(...){return L"";}}
bool VerifyFile(const std::wstring& path,const std::wstring& digest,unsigned long long expected){try{File f(CreateFileW(path.c_str(),GENERIC_READ,FILE_SHARE_READ,NULL,OPEN_EXISTING,FILE_FLAG_OPEN_REPARSE_POINT,NULL));BY_HANDLE_FILE_INFORMATION info;Require(GetFileInformationByHandle(f.h,&info)&&!(info.dwFileAttributes&(FILE_ATTRIBUTE_REPARSE_POINT|FILE_ATTRIBUTE_DIRECTORY))&&info.nNumberOfLinks==1,"Unsafe cached update");LARGE_INTEGER size;Require(GetFileSizeEx(f.h,&size)&&size.QuadPart>0&&(unsigned long long)size.QuadPart==expected&&expected<=MaximumInstaller,"Wrong file size");Digest hash;BYTE bytes[65536];DWORD count;do{Require(ReadFile(f.h,bytes,sizeof(bytes),&count,NULL)!=FALSE,"Read failed");hash.Add(bytes,count);}while(count);return hash.Finish()==digest;}catch(...){return false;}}

struct Service::State { mutable CRITICAL_SECTION mutex;Status status;std::wstring directory,current;bool safe;Fetcher fixture;std::atomic<bool> cancel{false};State(const std::wstring& p,const std::wstring& v,bool test,Fetcher fn):directory(p+L"\\Updates"),current(v),safe(test),fixture(fn){InitializeCriticalSection(&mutex);}~State(){DeleteCriticalSection(&mutex);}void Set(Phase phase,const std::wstring& message,int percent=0){Lock lock(mutex);status.phase=phase;status.message=message;status.percent=percent;} };
Service::Service(const std::wstring& directory,const std::wstring& version,bool safe,Fetcher fixture):state_(new State(directory,version,safe,fixture)){}
Service::~Service(){Cancel();if(worker_)CloseHandle(worker_);if(installer_)CloseHandle(installer_);}
void Service::Cancel(){state_->cancel=true;}
Status Service::Get()const{if(installer_&&WaitForSingleObject(installer_,0)==WAIT_OBJECT_0){DWORD code=1;GetExitCodeProcess(installer_,&code);CloseHandle(installer_);installer_=NULL;Lock lock(state_->mutex);state_->status.phase=code?Phase::Ready:Phase::Current;state_->status.elevation=code==5;state_->status.message=code==5?L"安装需要权限。点“以管理员权限安装”后由 Windows 确认。":code?L"安装未完成，原程序已保留。可手动重试。":L"安装程序已完成。";}Lock lock(state_->mutex);return state_->status;}
bool Service::Check(){if(worker_){if(WaitForSingleObject(worker_,0)!=WAIT_OBJECT_0)return false;CloseHandle(worker_);worker_=NULL;}if(state_->safe&&!state_->fixture){state_->Set(Phase::Disabled,L"安全预览中不联网、不安装更新。");return false;}std::vector<unsigned>parts;if(!Version(state_->current,parts)){state_->Set(Phase::Failed,L"无法读取当前版本，请使用正式安装包。");return false;}state_->cancel=false;state_->Set(Phase::Checking,L"正在检查 GitHub 最新正式版…");auto copy=new std::shared_ptr<State>(state_);worker_=CreateThread(NULL,0,Worker,copy,0,NULL);if(!worker_){delete copy;state_->Set(Phase::Failed,L"无法启动更新检查。");return false;}return true;}
DWORD WINAPI Service::Worker(void* raw){std::unique_ptr<std::shared_ptr<State>> holder((std::shared_ptr<State>*)raw);auto state=*holder;std::wstring temporary;try{auto fetch=[&](const std::wstring&url,size_t limit,const Sink&sink){Require(!state->cancel,"更新已取消");if(state->fixture)state->fixture(url,limit,sink);else HttpGet(url,limit,sink,state->cancel);};auto text=[&](const std::wstring& url,size_t limit){std::string result;fetch(url,limit,[&](const BYTE*data,size_t size){Require(size<=limit-result.size(),"Metadata too large");result.append((const char*)data,size);});return result;};Release release=ParseRelease(text(Latest,MaximumJson),state->current);if(release.version.empty()){state->Set(Phase::Current,L"当前已是最新正式版。");return 0;}if(release.digest.empty())release.digest=ManifestHash(text(release.manifestUrl,65536),release.filename);SafeDirectory(state->directory);std::wstring suffix=L"-"+std::to_wstring(GetCurrentProcessId())+L"-"+std::to_wstring(GetTickCount64());std::wstring final=state->directory+L"\\"+release.filename+suffix+L".exe";temporary=final+L".partial";File file(CreateFileW(temporary.c_str(),GENERIC_WRITE,0,NULL,CREATE_NEW,FILE_ATTRIBUTE_NORMAL|FILE_FLAG_OPEN_REPARSE_POINT,NULL));Digest hash;unsigned long long received=0;state->Set(Phase::Downloading,L"正在下载 Win7 更新…");fetch(release.assetUrl,(size_t)release.size,[&](const BYTE* bytes,size_t size){Require(!state->cancel&&size<=release.size-received,"下载数据超出预期");DWORD written=0;Require(WriteFile(file.h,bytes,(DWORD)size,&written,NULL)&&written==size,"无法保存更新文件");hash.Add(bytes,size);received+=size;state->Set(Phase::Downloading,L"正在下载 Win7 更新…",(int)(received*100/release.size));});Require(received==release.size&&hash.Finish()==release.digest,"更新文件校验失败，请重新检查更新");Require(FlushFileBuffers(file.h)!=FALSE,"无法保存更新缓存");file.Close();Require(FileVersion(temporary)==release.version,"安装包版本与 GitHub 发布版本不符");Require(!state->cancel&&MoveFileExW(temporary.c_str(),final.c_str(),MOVEFILE_WRITE_THROUGH),"更新已取消或缓存不可用");temporary.clear();{Lock lock(state->mutex);state->status.version=release.version;state->status.file=final;state->status.digest=release.digest;state->status.size=release.size;state->status.phase=Phase::Ready;state->status.percent=100;state->status.autoBlocked=RecentAttempt(state->directory,release.version);state->status.elevation=ReceiptNeedsElevation(state->directory,release.version);state->status.message=state->status.elevation?L"上次安装需要权限；可点以管理员权限安装，由 Windows 确认。":state->status.autoBlocked?L"此版本曾尝试安装，自动重试暂停 24 小时；可手动安装。":L"新版 "+release.version+L" 已下载并校验，等待空闲时安装。";}}catch(const std::exception&error){if(!temporary.empty())DeleteFileW(temporary.c_str());std::wstring message;try{message=Wide(error.what());}catch(...){message=L"网络或文件访问暂时不可用";}state->Set(Phase::Failed,L"更新未完成："+message+L"。稍后可重试。");}return 0;}
bool Service::Launch(HWND owner,const std::wstring& registered,bool manual){Status current=Get();if(current.phase!=Phase::Ready)return false;
#if defined(FI_CORE_TESTING) || defined(FI_UPDATE_TESTING)
 (void)owner;(void)registered;(void)manual;return false;
#else
 if(state_->safe||(!manual&&(registered.empty()||current.elevation||current.autoBlocked||ProcessElevated())))return false;if(!VerifyFile(current.file,current.digest,current.size)||FileVersion(current.file)!=current.version){state_->Set(Phase::Failed,L"更新缓存校验失败，请重新下载。");return false;}try{RecordAttempt(state_->directory,current.version);}catch(...){state_->Set(Phase::Failed,L"无法记录更新尝试，已保留当前版本。");return false;}std::wstring parameters=registered.empty()?L"":L"--auto-update \""+registered+L"\" --owner-sid \""+OwnerSid()+L"\"";SHELLEXECUTEINFOW launch={sizeof(launch)};launch.fMask=SEE_MASK_NOCLOSEPROCESS|SEE_MASK_FLAG_NO_UI;launch.hwnd=owner;launch.lpVerb=manual&&current.elevation?L"runas":L"open";launch.lpFile=current.file.c_str();launch.lpParameters=parameters.empty()?NULL:parameters.c_str();launch.nShow=registered.empty()?SW_SHOWNORMAL:SW_HIDE;if(!ShellExecuteExW(&launch)){state_->Set(Phase::Ready,L"安装尚未启动，可稍后重试。");return false;}installer_=launch.hProcess;state_->Set(Phase::Applying,registered.empty()?L"已打开安装包，请按安装向导操作。":L"正在更新，完成后会静默启动。");return true;
#endif
}
}
