#include "../src/update.h"
#include <wincrypt.h>
#include <iostream>
#include <stdexcept>
#include <string>
#include <vector>
#include <sstream>
using namespace fiUpdate;
static int checks=0;
static void Check(bool ok,const char* message){if(!ok)throw std::runtime_error(message);++checks;}
static void Reject(const std::function<void()>& action,const char* message){bool rejected=false;try{action();}catch(...){rejected=true;}Check(rejected,message);}
static std::string Narrow(const std::wstring& text){return std::string(text.begin(),text.end());}
static std::vector<BYTE> Read(const std::wstring& path){HANDLE file=CreateFileW(path.c_str(),GENERIC_READ,FILE_SHARE_READ,NULL,OPEN_EXISTING,0,NULL);Check(file!=INVALID_HANDLE_VALUE,"Fixture read");DWORD size=GetFileSize(file,NULL),count=0;std::vector<BYTE> bytes(size);BOOL ok=ReadFile(file,bytes.data(),size,&count,NULL);CloseHandle(file);Check(ok&&count==size,"Fixture complete");return bytes;}
static std::string Hash(const std::vector<BYTE>& data){HCRYPTPROV p=0;HCRYPTHASH h=0;Check(CryptAcquireContextW(&p,NULL,NULL,PROV_RSA_AES,CRYPT_VERIFYCONTEXT)&&CryptCreateHash(p,CALG_SHA_256,0,0,&h),"Test hash initialized");CryptHashData(h,data.data(),(DWORD)data.size(),0);BYTE hash[32];DWORD size=32;Check(CryptGetHashParam(h,HP_HASHVAL,hash,&size,0),"Test hash complete");CryptDestroyHash(h);CryptReleaseContext(p,0);const char* hex="0123456789abcdef";std::string s;for(BYTE b:hash){s+=hex[b>>4];s+=hex[b&15];}return s;}
static std::string ReleaseJson(const std::string& version,const std::string& hash,size_t size,bool manifest=false){std::string name="FreeIsland-Win7-Setup-"+version+".exe",prefix="https://github.com/Watertube-bilibili/free-island/releases/download/v"+version+"/";std::ostringstream s;s<<"{\"draft\":false,\"prerelease\":false,\"tag_name\":\"v"<<version<<"\",\"html_url\":\"https://github.com/Watertube-bilibili/free-island/releases/tag/v"<<version<<"\",\"assets\":[{\"name\":\""<<name<<"\",\"state\":\"uploaded\",\"size\":"<<size<<",\"browser_download_url\":\""<<prefix<<name<<"\",\"digest\":"<<(manifest?"null":"\"sha256:"+hash+"\"")<<"}";if(manifest)s<<",{\"name\":\"SHA256SUMS-"<<version<<".txt\",\"state\":\"uploaded\",\"size\":200,\"browser_download_url\":\""<<prefix<<"SHA256SUMS-"<<version<<".txt\"}";s<<"]}";return s.str();}
static Status Wait(Service& service){for(int i=0;i<600;i++){Status s=service.Get();if(s.phase!=Phase::Checking&&s.phase!=Phase::Downloading)return s;Sleep(10);}throw std::runtime_error("Fixture worker timed out");}
static void Put(const std::wstring& path,const std::string& value){HANDLE h=CreateFileW(path.c_str(),GENERIC_WRITE,0,NULL,CREATE_ALWAYS,FILE_ATTRIBUTE_NORMAL,NULL);Check(h!=INVALID_HANDLE_VALUE,"Write fixture");DWORD written;Check(WriteFile(h,value.data(),(DWORD)value.size(),&written,NULL)&&written==value.size(),"Write fixture complete");CloseHandle(h);}
int wmain(int argc,wchar_t** argv){try{
 Check(argc==2,"Provide new workspace test directory");std::wstring root=argv[1];Check(CreateDirectoryW(root.c_str(),NULL)!=FALSE,"Unique fixture root");
 Check(Newer(L"1.0.10",L"1.0.9")&&!Newer(L"1.0.7",L"1.0.7")&&!Newer(L"1.0.6",L"1.0.7"),"Numeric semantic versions");for(const wchar_t* v:{L"1.0.7-beta",L"01.0.8",L"1.0.8/../../",L"1.0",L"999999.0.0"})Check(!Newer(v,L"1.0.0"),"Invalid version blocked");
 Check(AllowedUrl(L"https://release-assets.githubusercontent.com/fixture?sig=abc"),"GitHub CDN redirect allowed");for(const wchar_t* u:{L"http://github.com/file",L"https://evil.test/file",L"https://github.com.evil.test/file",L"https://github.com:444/file",L"https://user@github.com/file",L"https://github.com/file#fragment"})Check(!AllowedUrl(u),"Untrusted redirect blocked");
 Check(CanApply(false,false,false,true),"Idle registered install allowed");Check(!CanApply(true,false,false,true)&&!CanApply(false,true,false,true)&&!CanApply(false,false,true,true)&&!CanApply(false,false,false,false),"Visible UI, timer, shutdown and portable block automatic install");
 wchar_t module[32768];GetModuleFileNameW(NULL,module,32768);auto bytes=Read(module);std::wstring version=FileVersion(module);Check(!version.empty(),"Fixture PE has version resource");std::string v=Narrow(version),hash=Hash(bytes),json=ReleaseJson(v,hash,bytes.size());Release metadata=ParseRelease(json,L"0.0.0");Check(metadata.version==version&&metadata.digest==std::wstring(hash.begin(),hash.end()),"Exact native asset selected");
 std::string bad=json;bad.replace(bad.find("\"draft\":false"),13,"\"draft\":true");Reject([&]{ParseRelease(bad,L"0.0.0");},"Draft rejected");bad=json;bad.replace(bad.find("Watertube-bilibili"),17,"other-owner");Reject([&]{ParseRelease(bad,L"0.0.0");},"Wrong repository rejected");bad=json;bad.replace(bad.find("\"assets\":"),9,"\"draft\":false,\"assets\":");Reject([&]{ParseRelease(bad,L"0.0.0");},"Duplicate JSON key rejected");Reject([&]{ParseRelease(std::string(1024*1024+1,'x'),L"0.0.0");},"Metadata bound");
 std::string filename="FreeIsland-Win7-Setup-"+v+".exe",manifest=hash+"  "+filename+"\r\n";Check(ManifestHash(manifest,std::wstring(filename.begin(),filename.end()))==metadata.digest,"Manifest fallback");Reject([&]{ManifestHash(manifest+manifest,std::wstring(filename.begin(),filename.end()));},"Duplicate checksum rejected");
 auto fetch=[&](const std::wstring& url,size_t limit,const Sink& sink){if(url.find(L"/latest")!=std::wstring::npos){sink((const BYTE*)json.data(),json.size());return;}if(url.find(L"SHA256SUMS")!=std::wstring::npos){sink((const BYTE*)manifest.data(),manifest.size());return;}Check(bytes.size()<=limit,"Declared asset bound");for(size_t at=0;at<bytes.size();at+=65536)sink(bytes.data()+at,std::min<size_t>(65536,bytes.size()-at));};
 Service good(root+L"\\good",L"0.0.0",true,fetch);Check(good.Check(),"Fixture check starts");Status ready=Wait(good);Check(ready.phase==Phase::Ready&&ready.percent==100&&VerifyFile(ready.file,ready.digest,ready.size),"Streamed installer SHA and PE version verified");Check(!good.Launch(NULL,L"",true),"Safe mode never launches installer");
 Service disabled(root+L"\\disabled",L"0.0.0",true);Check(!disabled.Check()&&disabled.Get().phase==Phase::Disabled,"Safe mode never uses real network");
 json=ReleaseJson(v,hash,bytes.size(),true);Service fallback(root+L"\\manifest",L"0.0.0",true,fetch);fallback.Check();Check(Wait(fallback).phase==Phase::Ready,"Manifest verified download");
 json=ReleaseJson(v,std::string(64,'0'),bytes.size());Service corrupt(root+L"\\bad-hash",L"0.0.0",true,fetch);corrupt.Check();Check(Wait(corrupt).phase==Phase::Failed,"Wrong SHA never ready");
 json=ReleaseJson("99.0.0",hash,bytes.size());Service wrongVersion(root+L"\\bad-version",L"0.0.0",true,fetch);wrongVersion.Check();Check(Wait(wrongVersion).phase==Phase::Failed,"Wrong embedded installer version never ready");
 json=ReleaseJson(v,hash,bytes.size());FILETIME ft;GetSystemTimeAsFileTime(&ft);ULARGE_INTEGER n;n.LowPart=ft.dwLowDateTime;n.HighPart=ft.dwHighDateTime;Put(root+L"\\good\\Updates\\attempt-"+version+L".txt",std::to_string(n.QuadPart/10000000ULL-11644473600ULL));Service retry(root+L"\\good",L"0.0.0",true,fetch);retry.Check();Check(Wait(retry).autoBlocked,"Failed or interrupted attempt suppresses automatic retry across restart");
 Put(root+L"\\good\\update-result.txt","failed\n"+v+"\n\xef\xbc\x88" "5" "\xef\xbc\x89");Service permissionRetry(root+L"\\good",L"0.0.0",true,fetch);permissionRetry.Check();Status permission=Wait(permissionRetry);Check(permission.autoBlocked&&permission.elevation,"Permission-needed receipt survives app restart for explicit UAC retry");
 std::cout<<"PASS: "<<checks<<" native updater checks; fixture-only transport, no network, installation, registry writes or process launch.\n";return 0;
 }catch(const std::exception&e){std::cerr<<"FAIL: "<<e.what()<<"\n";return 1;}}
